In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [4]:
x = np.array([1])
print(x)

[1]


## Q#2: Create y array with elements equal to 0.

In [8]:
y = np.array([0])
print(y)

[0]


## Q#3: Add x and y arrays.

In [9]:
xy = x+y
print(xy)

[1]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [14]:
print(f"Number of array dimensions: {x.ndim}")
print(f"Tuple of array dimensions: {x.shape}")
print(f"Number of elements in the array: {x.size}")
print(f"Data-type of the array’s elements: {x.dtype}")

Number of array dimensions: 1
Tuple of array dimensions: (1,)
Number of elements in the array: 1
Data-type of the array’s elements: int32


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [19]:
w = np.array([[11,12],[13,14],[15,16]])
print(w.shape)
w

(3, 2)


array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [22]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [44]:
newArray = np.hstack((w,np.reshape(z,(3,1))))
print(newArray)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [46]:
for row in newArray:
    for element in row:
        print(element)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [54]:
print("old: ", newArray)

# this should reverse the array
newArray= newArray[::-1]

print("\nnew: ", newArray)

old:  [[15 16  3]
 [13 14  2]
 [11 12  1]]

new:  [[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#10: Decrement all elements of "newArray" with 1.

In [55]:
newArray -= 1

print(newArray)

[[10 11  0]
 [12 13  1]
 [14 15  2]]


## Q#11: Find smallest and biggest values in "newArray".

In [59]:
print(f"biggest number in newArray array is: {newArray.max()}")

print(f"smallest number in newArray array is: {newArray.min()}")

biggest number in newArray array is: 15
smallest number in newArray array is: 0


## Q#12: Print the first row of "newArray" using indexing.

In [62]:
print(newArray[1][:]) # [:] could be removed

[12 13  1]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [66]:
'''
newArray =

   0  1   2
0 [10 11  0]
1 [12 13  1] < [1] 1
2 [14 15  2]
   ^
  [0] 2
'''

print(newArray[1][0])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [68]:
'''
newArray =

   0  1   2
0 [10 11  0] < [0] 1
1 [12 13  1] 
2 [14 15  2]
          ^
         [2] 2
'''

print(newArray[0][2])

0


## Q#15: Change the shape of "newArray" to (9,1).

In [73]:
newArray = newArray.reshape(9,1)
print(newArray)

[[10]
 [11]
 [ 0]
 [12]
 [13]
 [ 1]
 [14]
 [15]
 [ 2]]


## Q#16: Change the shape of "newArray" to (3,3).

In [74]:
newArray = newArray.reshape(3,3)
print(newArray)

[[10 11  0]
 [12 13  1]
 [14 15  2]]


# Well Done 🎉