In [9]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [10]:
x = np.ones([2,2])
print(x)

[[1. 1.]
 [1. 1.]]


## Q#2: Create y array with elements equal to 0.

In [11]:
y = np.zeros([2,2])
print(y)

[[0. 0.]
 [0. 0.]]


## Q#3: Add x and y arrays.

In [12]:
xy = x+y
print(xy)

[[1. 1.]
 [1. 1.]]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [13]:
print(f"Number of array dimensions: {x.ndim}")
print(f"Tuple of array dimensions: {x.shape}")
print(f"Number of elements in the array: {x.size}")
print(f"Data-type of the array’s elements: {x.dtype}")

Number of array dimensions: 2
Tuple of array dimensions: (2, 2)
Number of elements in the array: 4
Data-type of the array’s elements: float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [40]:
w = np.array([[11,12],[13,14],[15,16]])
print(w.shape)
w

(3, 2)


array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [41]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [42]:
z = np.reshape(z,(3,1))
newArray = np.hstack((w,z))
print(newArray)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [43]:
for row in newArray:
    for element in row:
        print(element)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [44]:
print("old: ", newArray)

# this should reverse the array
newArray= newArray.transpose()

print("\nnew: ", newArray)

old:  [[11 12  1]
 [13 14  2]
 [15 16  3]]

new:  [[11 13 15]
 [12 14 16]
 [ 1  2  3]]


## Q#10: Decrement all elements of "newArray" with 1.

In [45]:
newArray -= 1

print(newArray)

[[10 12 14]
 [11 13 15]
 [ 0  1  2]]


## Q#11: Find smallest and biggest values in "newArray".

In [46]:
print(f"biggest number in newArray array is: {newArray.max()}")

print(f"smallest number in newArray array is: {newArray.min()}")

biggest number in newArray array is: 15
smallest number in newArray array is: 0


## Q#12: Print the first row of "newArray" using indexing.

In [47]:
print(newArray[1][:]) # [:] could be removed

[11 13 15]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [49]:
'''
   newArray

   0  1   2
0 [10 12  14] < [0] 1
1 [11 13  15] 
2 [ 0  1   2]
      ^
     [1] 2
'''

print(newArray[0][1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [51]:
'''
   newArray

   0  1   2
0 [10 12  14]
1 [11 13  15] < [1] b1
2 [ 0  1   2] < [2] a1
   ^   ^
  [0] [1]
   a2  b2
'''
# a
print(f"equal 0: {newArray[2][0]}")

# b
print(f"equal 13: {newArray[1][1]}")

equal 0: 0
equal 13: 13


## Q#15: Change the shape of "newArray" to (9,1).

In [52]:
newArray = newArray.reshape(9,1)
print(newArray)

[[10]
 [12]
 [14]
 [11]
 [13]
 [15]
 [ 0]
 [ 1]
 [ 2]]


## Q#16: Change the shape of "newArray" to (3,3).

In [53]:
newArray = newArray.reshape(3,3)
print(newArray)

[[10 12 14]
 [11 13 15]
 [ 0  1  2]]


# Well Done 🎉